language: swift
osx_image: xcode10.2
xcode_project: Example.xcodeproj
xcode_scheme: Example
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone Xs
xcode_sdk: iphonesimulator12.2


before_script:
   - pod install

script:
   - echo "hello"
